# Generated by Django 5.2.17 on 2026-09-30 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("exercise", models.CharField(max_length=32)),
                ("level", models.PositiveSmallIntegerField()),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("question_count", models.PositiveSmallIntegerField()),
                ("correct_count", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["-ended_at"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root_midi", models.PositiveSmallIntegerField()),
                ("interval_semitones", models.PositiveSmallIntegerField()),
                ("mode", models.CharField(max_length=16)),
                ("answered_semitones", models.PositiveSmallIntegerField()),
                ("correct", models.BooleanField()),
                ("response_ms", models.PositiveIntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="progress.session",
                    ),
                ),
            ],
        ),
    ]
