# Generated by Django 5.2.17 on 2026-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_generalise_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("item", models.CharField(max_length=16)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("done", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "item"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "item"), name="one_log_per_item_per_day"
                    )
                ],
            },
        ),
    ]
