# Generated by Django 5.2.17 on 2026-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_practicelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="local_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
